#!/bin/bash

# New implementation

# +DMA +load_balancing +concurrency +remapping_scatter
# -bulk_read_split -threashold_read -threshold_write

DMA_EN=1
CONCURR_EN=1
W_THRSH_EN=0
R_THRESH_EN=0
R_CHUNK_EN=0
SCATTER_EN=1

source ${PROFILE_BASE_DIR}/common/common_setup
