#!/bin/bash

# Dummy
# DMA No-opt + Concurrency (Old version, manual test)

# +DMA +load_balancing +concurrency (Old impl.)
# -remapping_scatter -bulk_read_split -threashold_read -threshold_write

echo "This file should not be included!!!"
exit 1
